# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_text',
            field=models.IntegerField(default=0),
        ),
    ]
