# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170501_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_text',
            field=models.CharField(max_length=1),
        ),
    ]
